version: '3.4'

services:
  productdb:
    image: mongo
  microservice.product:
    image: ${DOCKER_REGISTRY-}microserviceproduct
    build:
      context: .
      dockerfile: MicroService.Product/Dockerfile
  microservice.sourcing:
    image: ${DOCKER_REGISTRY-}microservicesourcing
    build:
      context: .
      dockerfile: MicroService.Sourcing/Dockerfile

volumes:
  mongo_data:

